; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
AppName=RegtelDaemon
AppVerName=RegtelDaemon v3.0
AppPublisher=Registro Telemático
AppPublisherURL=www.redabogacia.org
AppSupportURL=www.redabogacia.org
AppUpdatesURL=www.redabogacia.org
DefaultDirName=C:/CGAE\REGTEL
;DisableDirPage=yes
DefaultGroupName=CGAE
InfoBeforeFile=D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\discurso_instalacion.rtf
InfoAfterFile=D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\discurso__despues_instalacion.rtf
OutputDir=D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\Output
OutputBaseFilename=RegtelDaemon_setup
SetupIconFile=D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\ICONO_REGTEL.ico
Compression=lzma
SolidCompression=yes
UninstallDisplayName=RegtelDaemon
;pregunta si hay que reiniciar windows
AlwaysRestart=yes
SourceDir=C:\

[Languages]
Name: "esp"; MessagesFile: "compiler:Languages/Spanish.isl"

[Tasks]
; Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\RegtelDaemon.jar"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\Instalar_Servicio_RegtelDaemon.bat"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\Desinstalar_Servicio_RegtelDaemon.bat"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\EjecutarREGTEL.bat"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\MIN.EXE"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\my.keystore"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\regtelDaemoIni.properties"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\imagenes\*"; DestDir: "{app}\imagenes"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\TrayIcon12.dll"; DestDir: "{sys}"; Flags: onlyifdoesntexist
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\jdk\*"; DestDir: "{app}\jdk"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\ICONO_REGTEL.ico"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\WorkSpace_Helios_2\Core\installer\Daemon_scr\REGTEL\RegtelDaemon\Daemon_src\JavaService.exe"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs


